### ISSUE TITLE
Mobile plans

### ISSUE THREAD

**Issue by jeffpooley** [coddingtonbear/obsidian-local-rest-api#1]
This looks immensely useful—thank you! Do you have plans to enable for mobile? With iPad-only users in particular, building Shortcuts  with the api will be a game changer.

**Comment by coddingtonbear** [comment]
Oh, I wish!  Unfortunately, I believe it's impossible on mobile given that access to node packages isn't available in that environment, and this, as you might expect, relies on the node `http` and `https` packages.  Cheers!
