### ISSUE TITLE
2.0.5 got incorrectly tagged as a release, now can't install/update

### ISSUE THREAD

**Issue by luckman212** [coddingtonbear/obsidian-local-rest-api#101]
minor: 2.0.5 got incorrectly tagged as a release, now can't install/update from inside Obsidian.

**Comment by owrede** [comment]
Me too.

**Comment by littledogboy** [comment]
same error tome

**Comment by xiel0325** [comment]
So what should I do?

**Comment by Tback1** [comment]
me too~ and not find the 2.0.5 in the git release page

**Comment by owrede** [comment]
I tried that ... but I was not succsessful. I do not understand which files I need to be putting into the plugin folder (Sorry). 

The plugin folder has four files:

- data.json	
- main.js		
- manifest.json
- styles.css

I the repo here I find many other and all code files are TypeScript (.ts) files. I was assuming that Obsidian does some sort of compiling from TypeScript to JavaScript when installing a plugin.

**Comment by Tback1** [comment]
> I tried that ... but I was not succsessful. I do not understand which files I need to be putting into the plugin folder (Sorry).我试过了......但我没有成功。我不明白我需要将哪些文件放入插件文件夹（对不起）。
> 
> The plugin folder has four files:插件文件夹有四个文件：
> 
> * data.json
> * main.js 主 .js
> * manifest.json
> * styles.css 样式 .css
> 
> I the repo here I find many other and all code files are TypeScript (.ts) files. I was assuming that Obsidian does some sort of compiling from TypeScript to JavaScript when installing a plugin.我在这里的存储库中发现了许多其他代码文件，所有代码文件都是 TypeScript （.ts） 文件。我假设 Obsidian 在安装插件时会从 TypeScript 编译到 JavaScript。

no you just need 
```
styles.css
main.js
data.json
manifest.json
```

**Comment by owrede** [comment]
I am not sure what you mean.
In this repository here I see _styles.css_ and _manifest.json_. 
I do not see _data.json_ or _main.js_.

What am I missing?

![image](https://github.com/coddingtonbear/obsidian-local-rest-api/assets/2369810/86309d62-2f63-4ac5-aba4-4ff9d1124245)

**Comment by owrede** [comment]
OK. I got it. There was a build error for 2.0.5 that prevented the deployment of the files needed:
https://github.com/coddingtonbear/obsidian-local-rest-api/actions/runs/7601968816/job/20701963503

I guess that's why people can't update to 2.0.5.

**Comment by codethought** [comment]
Well hopefully @coddingtonbear sees this discussion sometime soon and get it fixed.

**Comment by MatiasVerdier** [comment]
As a temporary solution you can install the previous version of the plugin (2.0.4) using [BRAT](https://github.com/TfTHacker/obsidian42-brat)

1. Install BRAT plugin
![image](https://github.com/coddingtonbear/obsidian-local-rest-api/assets/5176883/45593aee-9cee-43b4-bbe3-0cc08cee4003)

2. Add plugin with frozen version
![image](https://github.com/coddingtonbear/obsidian-local-rest-api/assets/5176883/2191ba77-ef3b-4de1-a16d-91167ccd9d51)

3. Paste repo URL and version
![image](https://github.com/coddingtonbear/obsidian-local-rest-api/assets/5176883/484e3842-be5a-46f0-b7f9-6350da1335ef)

Hope it helps

**Comment by Tback1** [comment]
just compile error，but @coddingtonbear may be on vacation, so need wait he back to deal it

**Comment by coddingtonbear** [comment]
Whoops! So that will teach me for trying to squeeze in a small fix for somebody when I found myself with a (very) few minutes of free time before a vacation.

I've re-released as 2.0.6 (after re-building `package-lock.json`) and things should install correctly once again.

**Comment by owrede** [comment]
Update went fine! Thanks (still have a problem though... posted in a new issue)
