### ISSUE TITLE
The icon shows“ERR”

### ISSUE THREAD

**Issue by EgnaroJQ** [coddingtonbear/obsidian-local-rest-api#103]
As attached.
I do not know what is the problem.
The Api key has been correctedly set. 
I use Mac, and my obsidian vault is in icloud. Is that the problem?
<img width="40" alt="截屏2024-01-25 20 29 41" src="https://github.com/coddingtonbear/obsidian-local-rest-api/assets/74129216/3b6f0ba3-40ed-4ff7-b683-ab3da250ebfe">

**Comment by wsw70** [comment]
I have the same problem. I uninstalled and tried to reinstall the plugin but it fails to install (with just a message "Failed to install"). Is there a log where I could try to debug what is going on?

**Comment by Tback1** [comment]
this is same as this [issus](https://github.com/coddingtonbear/obsidian-web/discussions/157) of obsidian-web,it should fixed in the next release

**Comment by logan00000000** [comment]
ME TOO

**Comment by coddingtonbear** [comment]
This is a duplicate of #101
