### ISSUE TITLE
Non-ascii folder names are not supported

### ISSUE THREAD

**Issue by beaussan** [coddingtonbear/obsidian-local-rest-api#13]
Hi,

I have emoji in my folder names (in order to replicate notion's folder icons), and from some initial testing, there seems to be some issue with that : 

### GET on /vault/filename

Yield to the following error in the obsidian console : 
`node:internal/errors:464 Uncaught (in promise) TypeError: Invalid character in header content ["Content-Disposition"]`

### GET on /periodic/period

Yield the following error in the obsidian console :  
`TypeError: Invalid character in header content ["Content-Location"]`

---

All request were done on the provided swagger UI, and all requests hangs instead of returning a 500 error, maybe that can also be a improvement ?

And I want to say, I love the idea of the plugin, there is soo much potential to be plugged to external tools, but since nearly all of my files are in a folder that contains a emoji name, I'm not able to use this plugin

**Comment by beaussan** [comment]
Thanks for fixing the first one (/vault/filename), however the one with the content-location header still breaks, maybe applying the same escape system ? 

Reproduction :  
GET /periodic/daily
With a folder name "🖊️ journal/"

Workaround : using the /vault/filename works

**Comment by ngirard** [comment]
> Now I can experiment to create workflow using the api

This tickles my curiosity... would you mind expanding on that ? Cheers !

**Comment by beaussan** [comment]
> This tickles my curiosity... would you mind expanding on that ?
Yes, some of my plans includes

* Making a api (using something like n8n + postgresql as a buffer) to be able to programmaticaly insert in my vault's workbench from webhooks / external apis
* Extracting metrics from my daily notes (from the dataview keys in the files) into a external dashboard
* Keeping in one way - or maybe two way sync - between obsidian and a external tool (like notion) for teams

I could use the filesystem for all of this, but it makes it easier it easier to do in a distributed manner (as in I can have a full time running server to receive the webhooks and then do pulling after it's stored once Obsidian is up)
