### ISSUE TITLE
Chrome does not store the authority certificate

### ISSUE THREAD

**Issue by twilwa** [coddingtonbear/obsidian-local-rest-api#130]
Little bit of a quirk and didn't used to happen, I don't think -- I have to re-import the generated cert on any new chrome session. Lmk if there's anything I should test or logs I should grab :)

**Comment by coddingtonbear** [comment]
Unfortunately, although this browser extension runs on Chrome, I'm not a Chrome maintainer.  If you reach out on https://support.google.com/chrome/community?hl=en they may be able to point you in the right direction!  Good luck!
