### ISSUE TITLE
Obsidian says Local REST API version 3.0.0 is available for update, yet I find no evidence it exists. 

### ISSUE THREAD

**Issue by clinkenb** [coddingtonbear/obsidian-local-rest-api#134]
![Screenshot 2024-11-06 at 14 43 52](https://github.com/user-attachments/assets/c1cf981f-e969-4a02-b05d-d59fa7e8f6e5)

**Comment by clinkenb** [comment]
It seems the tag for a 3.0.0 exists, but there is no release for that version evident.

![Screenshot 2024-11-06 at 14 50 18](https://github.com/user-attachments/assets/04289e15-0459-4437-86cf-816b61a9212b)

**Comment by laye0619** [comment]
update failed here... the same problem.

**Comment by coddingtonbear** [comment]
Yeah!  I ran into a little bit of a problem publishing the latest version of this package, and can't find the time right now to fix it.  For now, just stick on the current 2.x version.

**Comment by coddingtonbear** [comment]
I found a little bit of time this morning, and I believe I've fixed this now.  Good luck!
