### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by Shtooth** [coddingtonbear/obsidian-local-rest-api#135]
While trying to install the plugin in Obsidian there seem to be an error (image below)

![image](https://github.com/user-attachments/assets/240991a3-a016-4987-878d-1b9420521396)

The console displays a 404 error
![image](https://github.com/user-attachments/assets/8259d379-ec04-4d33-a02e-3b432c809ab4)

**Comment by azigler** [comment]
Temporary workaround:

1. [Download `v2.5.4`](https://github.com/coddingtonbear/obsidian-local-rest-api/releases/tag/2.5.4)
2. Unzip to `.obsidian/plugins` in your vault
3. Add `"obsidian-local-rest-api"` to the array in `.obsidian/community-plugins.json` in your vault

**Comment by eXperitur** [comment]
Plugin update also failing for me, even after updating manually from [v2.5.4](https://github.com/coddingtonbear/obsidian-local-rest-api/releases/tag/2.5.4). 

I noticed the version of the download zip file name on the releases page for [v2.5.4](https://github.com/coddingtonbear/obsidian-local-rest-api/releases/tag/2.5.4) isn't matching ([obsidian-local-rest-api-2.4.3.zip](https://github.com/coddingtonbear/obsidian-local-rest-api/releases/download/2.5.4/obsidian-local-rest-api-2.4.3.zip)). Could that be why?

**Comment by dahifi** [comment]
@azigler Work around on fresh install (MacOS) was fine. 

For others, make sure the plugin folder reflects the string you added to json, as @eXperitur alluded to above.

**Comment by coddingtonbear** [comment]
I found a little bit of time today, and I think things should be fixed up now.  Good luck!
