### ISSUE TITLE
The server is not responding  when Searching for documents matching a specified gui-evaluated query

### ISSUE THREAD

**Issue by wolovejing** [coddingtonbear/obsidian-local-rest-api#14]
![image](https://user-images.githubusercontent.com/30975494/161037844-19e7e3f8-c2fe-44d7-adc7-07ea1ba66ecf.png)

**Comment by wolovejing** [comment]
![image](https://user-images.githubusercontent.com/30975494/161040642-25e65735-8d99-4d5e-bfdd-cfc5452328e2.png)

**Comment by coddingtonbear** [comment]
So, this particular feature _will_ probably be a little fragile given that we're relying on an undocumented interface, but I did just check it a moment ago and wasn't able to reproduce the problem you're seeing above.  I've just right now tested on Linux (AppImage) using v0.14.7, but do know that it also worked when I wrote this a couple months ago; so I don't imagine the interface has changed substantially.

I'm afraid I'll need some more information from you before I can make a guess; maybe start with:

- What OS are you running on?
- What version of Obsidian are you using?
- Does the search string you're searching for actually have matches?
- Do you see search results appear in the Obsidian UI when you perform this search?

& really anything else you can think of that might help.

**Comment by coddingtonbear** [comment]
Closing due to lack of response.
