### ISSUE TITLE
IOS problem

### ISSUE THREAD

**Issue by springrain1** [coddingtonbear/obsidian-local-rest-api#16]
The mobile plug-in switch cannot be turned on [obsidian-local-rest-api] ，IOS Obsidian V1.2.0 is not supported. Hope the developer can solve it soon, thank you!

**Comment by coddingtonbear** [comment]
This is, unfortunately, not fixable -- this library uses many node modules that are unavailable on IOS; so installation on mobile devices is disabled (see https://github.com/coddingtonbear/obsidian-local-rest-api/blob/main/manifest.json#L9).
