### ISSUE TITLE
[Bug] GET /vault/{pathToDirectory} doesn't return 404 not found error

### ISSUE THREAD

**Issue by kaiiiz** [coddingtonbear/obsidian-local-rest-api#22]
Consider the following folder structure:

```
.
├── a
│   └── a.md
└── b
```

What I get from the server response:

<img width="1266" alt="image" src="https://user-images.githubusercontent.com/30596812/169664617-47b99a0b-89d5-4c23-b10b-2177540f2bb1.png">

What I expected to get from the server response:

It should return 404 (Directory does not exist) instead of 200.

OS: MacOS Monterey 12.2.1 (M1)
Obsidian version: 0.14.6
Obsidian local rest API version: 1.3.5

**Comment by coddingtonbear** [comment]
Fixed in d011f40; thanks for this bug report, too, @kaiiiz !
