### ISSUE TITLE
[Bug] Server hang after requesting folder for file-related `/vault/{filename}` endpoints

### ISSUE THREAD

**Issue by kaiiiz** [coddingtonbear/obsidian-local-rest-api#23]
Consider the following folder structure:

```
.
├── a
│   └── a.md
└── b
```

Request `/vault/{filename}` related endpoints with `filename = a` (`a` is a folder, not a valid file).

What I get from the server response: It's completely hung.

<img width="1275" alt="image" src="https://user-images.githubusercontent.com/30596812/169664771-1ec78fdb-e37a-4f80-93bb-7957735e193d.png">

Similar results can get from `GET`, `PUT`, `POST`, `DELETE` endpoints.

What I expected to get from the server response:

It should return some errors instead of hanging (maybe 405 Bad Request?)

OS: MacOS Monterey 12.2.1 (M1)
Obsidian version: 0.14.6
Obsidian local rest API version: 1.3.5

**Comment by kaiiiz** [comment]
I notice a related issue, for the PUT `/vault/{filename}` endpoint, if the specified folder in the path doesn't exist, the server is hung forever. (e.g. `filename = c/d.md` and folder `c` doesn't exist)

<img width="1152" alt="image" src="https://user-images.githubusercontent.com/30596812/169708729-c2993abf-332d-49aa-80c9-29964b382333.png">

What I expected to get from the server response:

It should return 405 Bad Request or create the nested folder structure before creating the new file (maybe an optional parameter for this functionality?).

**Comment by coddingtonbear** [comment]
> I notice a related issue, for the PUT `/vault/{filename}` endpoint, if the specified folder in the path doesn't exist, the server will hang forever. (e.g. `filename = c/d.md` and folder `c` doesn't exist)
> 
> <img alt="image" width="1152" src="https://user-images.githubusercontent.com/30596812/169708729-c2993abf-332d-49aa-80c9-29964b382333.png">
> 
> What I expected to get from the server response:
> 
> It should return 405 Bad Request or create the nested folder structure before creating the new file (maybe an optional parameter for this functionality?).

For this issue -^ I've created #24.

**Comment by coddingtonbear** [comment]
Thanks for another very thorough bug report; I've fixed this in c9bc41e.
