### ISSUE TITLE
Flexible PATCH support

### ISSUE THREAD

**Issue by coddingtonbear** [coddingtonbear/obsidian-local-rest-api#26]
Follow https://github.com/coddingtonbear/obsidian-local-rest-api/wiki/Flexible-PATCH for details.

**Comment by joezimjs** [comment]
Can this be used to insert Front Matter? And how would a user find a block reference ID?

**Comment by joezimjs** [comment]
> Can this be used to insert Front Matter? And how would a user find a block reference ID?

Are block reference IDs the things you create with the carets? ^hereBeAnID?

**Comment by Moyf** [comment]
Hello! I am wondering if is it possible to insert content into a specific position under a Heading while ignoring its sub-heading?

For instance, I would like to insert new text at this location using `PATCH`:
![image](https://github.com/user-attachments/assets/b9fd2301-121e-4290-bc96-1fb9423f42be)

However, at prsent, I am only able to insert content at these locations (based on the `Content-Insertion-Position`):
![image](https://github.com/user-attachments/assets/d0484e06-43e1-4815-b09a-0c6a5ebc9478)

---

My parameters:
![image](https://github.com/user-attachments/assets/fc9e32f3-c90e-46aa-bf44-90e15bc465dc)

And if it's not supported at present, could you consider adding another param (`Ignore SubHeading`?) or using `Timestamp::Timestamp` to indicate the Heading itself? 🤔

**Comment by coddingtonbear** [comment]
This was released as part of v3.0.
