### ISSUE TITLE
"Failed to load plugin [...]" when enabling

### ISSUE THREAD

**Issue by cs-mshah** [coddingtonbear/obsidian-local-rest-api#6]
![image](https://user-images.githubusercontent.com/56499208/156913065-b33c2284-8dd0-4805-b607-1a37fb7991ea.png)

After installing and clicking enable, it showed this error

**Comment by ngirard** [comment]
@cs-mshah, which OS are you running ?

Also which Obsidian and local-rest-api versions are you using ?

**Comment by cs-mshah** [comment]
ubuntu 20.04, obsidian v13.23, plugin v1.3.1

**Comment by ngirard** [comment]
Alright. Which packaging format are you using then ? Could you try using an alternate pakaging format ?

FWIW I'm running plugin v1.3.1 on Obsidian v0.13.28 and Ubuntu 21.10 and I'm not experiencing this defect.

**Comment by cs-mshah** [comment]
What do you mean by packaging format? I installed obsidian via snap and the plugin from the internal community plugins

**Comment by ngirard** [comment]
Then I'd suggest giving the AppImage package a try. No guarantees here, but I happen to be using the AppImage format.

**Comment by coddingtonbear** [comment]
@cs-mshah -- could you check the dev console (Ctrl+Shift+I) to see what error is shown there when you try to enable the plugin?  Unfortunately the error message you've shown above is just the one Obsidian itself surfaces, and it doesn't really tell us much other than "something went wrong".

**Comment by hellopersonn** [comment]
I have the same problem Im on windows 10, obsidian v0.13.31, plugin v1.3.1 
<img width="416" alt="Obsidian_fAjCGzL4Kw" src="https://user-images.githubusercontent.com/101227790/157348124-5b5ebf67-e3de-4bca-a6a5-280befcbe643.png">

**Comment by sakgoag** [comment]
> I have the same problem Im on windows 10, obsidian v0.13.31, plugin v1.3.1 <img alt="Obsidian_fAjCGzL4Kw" width="416" src="https://user-images.githubusercontent.com/101227790/157348124-5b5ebf67-e3de-4bca-a6a5-280befcbe643.png">
 Same error for me

**Comment by Mlk1225** [comment]
The same problem in win10, obsidian v0.13.33, plugin v1.3.1
![image](https://user-images.githubusercontent.com/99351271/162785111-cded2714-7634-47c2-b9a3-f1272668cd44.png)

**Comment by coddingtonbear** [comment]
@Mlk1225 -- _clearly_ that's a very different traceback than the one described above; so I think you should probably file a different issue.  I've deleted your comment here so as to make sure the conversation sticks to covering only this problem.

**Comment by lenxvp** [comment]
I have the same problem on windows 10, obsidian v0.14.5, plugin v1.3.1

**Comment by kiwiflydream** [comment]
I have the same problem on macOS monterey , obsidian v0.14.6, plugin v1.3.1

**Comment by kiwiflydream** [comment]
> I have the same problem on macOS monterey , obsidian v0.14.6, plugin v1.3.1

I re-downloaded obsidian and installed it as an overwrite and it worked

**Comment by sakgoag** [comment]
> > I have the same problem on macOS monterey , obsidian v0.14.6, plugin v1.3.1
> 
> I re-downloaded obsidian and installed it as an overwrite and it worked

Yup confirmed, installed fine for me now. Nice one!

**Comment by coddingtonbear** [comment]
My _guess_ would be, then, that this is a limitation in the Obsidian installer version:

![image](https://user-images.githubusercontent.com/527661/163689013-3238b505-4e75-4222-8d5c-67928b135445.png)

When you re-download Obsidian and install it as an overwrite, you're updating both Obsidian and the installer.

If anybody else runs into this same problem in the future, could you first note what your installer version is (see the above screenshot); then verify that just re-downloading & installing Obsdian fixes your problem as @kiwiflydream discovered above?

If it _doesn't_, please comment here.
