### ISSUE TITLE
POST /search/gui meets searchDom.children is not iterable

### ISSUE THREAD

**Issue by Kherrisan** [coddingtonbear/obsidian-local-rest-api#71]
```
{
  "message": "Internal Server Error\nsearchDom.children is not iterable",
  "errorCode": 50000
}
```

![](https://cdn.staticaly.com/gh/Kherrisan/picx-images-hosting@master/202308291207936.png)

I am not sure whether `searchDorm.children` is an alias for `searchDom.vChildren._children` or not, due to some underlying dynamic attribute binding features. Anyway, i replaced `.children` with `.vChildren._children` and it worked.

Besides, another crash happened as follows:

```
{
  "message": "Internal Server Error\nresult.result.content is not iterable",
  "errorCode": 50000
}
```

![](https://cdn.staticaly.com/gh/Kherrisan/picx-images-hosting@master/202308291205003.png)

I found that it happened when the query text matches the file name, but the file content doesn't contain any matched text.

![](https://cdn.staticaly.com/gh/Kherrisan/picx-images-hosting@master/202308291215752.png)

Some version info:
- Obsidian: 1.3.7
- Local REST API: 1.6.0
- (If necessary) Obsidian theme: Minimal

**Comment by coddingtonbear** [comment]
Yes, the /gui/ search was always going to be very brittle given that that is not a documented API.

There are two ways we could take this:

1. Maybe you (or somebody else here) could find the problem and post a pull request that fixes the /gui/ search?
2. I could remove this API in the next version given that it will require more maintenance over time than I can reasonably commit.

:crossed_fingers: that you file a PR!
