### ISSUE TITLE
bug: can’t write binary file 

### ISSUE THREAD

**Issue by rowthan** [coddingtonbear/obsidian-local-rest-api#88]
i tried write a image file called by put method but faild.

i think it’s a problem in this method 
`_vaultPut` .  why it prevent write binary files?

**Comment by rowthan** [comment]
i have made a pull request to solve this problem.  check it please #89

**Comment by coddingtonbear** [comment]
I wonder if you could elaborate on the problem you might've been experiencing -- I'm vaguely aware that we do handle binary content _as long as the content-type_ header is set correctly.   What error message are you seeing?

**Comment by coddingtonbear** [comment]
Fixed via release 2.0.0.
