### ISSUE TITLE
Cannot read properties of undefined (reading 'getDailyNoteSettings') when querying /periodic/daily

### ISSUE THREAD

**Issue by lstep** [coddingtonbear/obsidian-local-rest-api#93]
Using version 2.0.3, when running a GET (same for PATCH) on /periodic/daily, returns an error. It was working fine before.

```bash
curl -X 'GET' \
  'http://127.0.0.1:27123/periodic/daily/' \
  -H 'accept: text/markdown' \
  -H 'Authorization: Bearer xxxxxxxxxxxxxxxxxxxxxxxxxxx'
```

Got:

```bash
{
  "message": "Internal Server Error\nCannot read properties of undefined (reading 'getDailyNoteSettings')",
  "errorCode": 50000
}
```

**Comment by coddingtonbear** [comment]
This looks like it's related to some changes in `esbuild` (the bundler we use); so I've reverted to an earlier version of esbuild and re-published as v2.0.4.  Things look like they work just fine now!
